[General]
firstTime=false
windowGeometry=@Rect(7 53 948 1020)
windowMaximized=false
windowState=@ByteArray(\0\0\0\xff\0\0\0\0\xfd\0\0\0\0\0\0\x3\xb4\0\0\x3\xb5\0\0\0\x4\0\0\0\x4\0\0\0\b\0\0\0\b\xfc\0\0\0\x1\0\0\0\x2\0\0\0\x1\0\0\0\x16\0\x45\0\x64\0i\0t\0T\0o\0o\0l\0\x42\0\x61\0r\x1\0\0\0\0\xff\xff\xff\xff\0\0\0\0\0\0\0\0)

[AppSettings]
appMode=0
defaultJpgQuality=97
firstTime.nomacs.3=false

[CustomPluginShortcuts]
Composite%20Image=Composite Image
Crop%20to%20Metadata=Crop to Metadata
Crop%20to%20Page=Crop to Page
Draw%20to%20Page=Draw to Page
Fake%20Miniatures=Fake Miniatures
Image%20Transform=Image Transform
Paint%20on%20Image=Paint on Image

[DisplaySettings]
bgColorNoMacsRGBA=4281678149
bgColorWidgetRGBA=2852126720
fgColorNoMacsRGBA=4292074211
fontColorRGBA=4292730333
highlightColorRGBA=4278216379
iconColorRGBA=4292074211
stylePlugin=kvantum
themeName312=System.css

[DkAppManager]
Apps\1\appName=&File Manager
Apps\1\appPath=OpenDir
Apps\1\objectName=OpenDir
Apps\2\appName=&Default Application
Apps\2\appPath=OpenFile
Apps\2\objectName=OpenFile
Apps\size=2

[DkCentralWidget]
Tabs\1\tabMode=2
Tabs\2\tabMode=3
Tabs\size=2

[DkDialog]
deleteFileDialog=true
deleteFileDialog-answer=16384
saveTabsDialog=true
saveTabsDialog-answer=16384

[DkFilePreview]
windowPosition=1

[DkMetaDataHUD]
keyValues=File.Filename, File.Path, File.Size, Exif.Image.Make, Exif.Image.Model, Exif.Image.DateTime, Exif.Image.ImageDescription, Exif.Photo.UserComment, Exif.Photo.ISO, Exif.Photo.FocalLength, Exif.Photo.ExposureTime, Exif.Photo.Flash, Exif.Photo.FNumber
numColumns=-1
windowPosition=3

[GlobalSettings]
recentFiles=/home/erik/Videos/Peek 2026-05-26 13-54.gif, /home/erik/KIRO/kiro-calamares-config-next/etc/calamares/branding/kiro/01cal.jpg, /home/erik/KIRO/kiro-calamares-config-next/etc/calamares/branding/kiro/squid.png, /home/erik/KIRO/kiro-calamares-config-next/etc/calamares/branding/kiro/logo.png, /home/erik/Downloads/kiro-brand-kit (1)/favicon-512.png, /home/erik/Downloads/kiro-brand-kit (1)/logo.png, /tmp/kiro-take5.png, /tmp/kiro-real.png, /tmp/kiro-frame2.png, /tmp/kiro-frame.png, /home/erik/EDU/edu-system-files/usr/share/icons/hicolor/logo.png, /home/erik/KIRO/kiro_repo/kiro-chadwm.jpg, /home/erik/Insync/Kiro/OLD/Logo-Erik/current/logo-fun.png, /home/erik/KIRO/kiro-website/assets/branding/favicon-192.png, /home/erik/KIRO/kiro-website/assets/branding/logo.png, /home/erik/KIRO/kiro-website/assets/branding/favicon-48.png, /home/erik/EDU/plymouth-theme-startrek/usr/share/plymouth/themes/startrek/glow.png
recentFolders=/home/erik/Videos, /home/erik/KIRO/kiro-calamares-config-next/etc/calamares/branding/kiro, /home/erik/Downloads/kiro-brand-kit (1), /tmp, /home/erik/EDU/edu-system-files/usr/share/icons/hicolor, /home/erik/KIRO/kiro_repo, /home/erik/Insync/Kiro/OLD/Logo-Erik/current, /home/erik/KIRO/kiro-website/assets/branding, /home/erik/EDU/plymouth-theme-startrek/usr/share/plymouth/themes/startrek

[Page%20Extraction%20Plugin]
Method=0

[SynchronizeSettings]
checkForUpdates=true
disableUpdateInteraction=false

[zooming]
useLevels=false
zoomLevels="0.0001,0.001,0.01,0.05,0.1,0.125,0.166,0.25,0.333,0.5,0.66,1,1.5,2,3,4,5,6,7,8,12,16,32,64,128"
